### ISSUE TITLE
LORE trainning log

### ISSUE THREAD

**Issue by SCUT-ChenBD** [AlibabaResearch/AdvancedLiterateMachinery#123]
During the training process, at what level did the final loss stabilize? Can you publish your training log?

**Comment by vvvvvair** [comment]
how to solve this problem？

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from datasets.dataset_factory import get_dataset
ModuleNotFoundError: No module named 'datasets.dataset_factory'

**Comment by vvvvvair** [comment]
> During the training process, at what level did the final loss stabilize? Can you publish your training log?

Please ，how to solve this problem during  the training process？

Traceback (most recent call last):
File "main.py", line 15, in
from datasets.dataset_factory import get_dataset
ModuleNotFoundError: No module named 'datasets.dataset_factory'
