### ISSUE TITLE
ImportError: cannot import name '_datasets_server' from 'datasets.utils'

### ISSUE THREAD

**Issue by decadance-dance** [AlibabaResearch/AdvancedLiterateMachinery#129]
I am trying to run `python example.py document_structurization ...`
I get this error: 
```
2024-04-19 10:07:31,200 - modelscope - INFO - PyTorch version 2.2.2 Found.
2024-04-19 10:07:31,201 - modelscope - INFO - Loading ast index from /home/dmytrodronov/.cache/modelscope/ast_indexer
2024-04-19 10:07:31,239 - modelscope - INFO - Loading done! Current index file version is 1.13.3, with md5 7d51058497160033a2c8de2fc3002ba8 and a total number of 972 components indexed
Traceback (most recent call last):
  File "/home/dmytrodronov/AdvancedLiterateMachinery/Applications/DocXChain/example.py", line 16, in <module>
    from pipelines.general_text_reading import GeneralTextReading
  File "/home/dmytrodronov/AdvancedLiterateMachinery/Applications/DocXChain/pipelines/general_text_reading.py", line 9, in <module>
    from modules.text_detection import TextDetection
  File "/home/dmytrodronov/AdvancedLiterateMachinery/Applications/DocXChain/modules/text_detection.py", line 12, in <module>
    from modelscope.pipelines import pipeline
  File "/home/dmytrodronov/miniconda3/envs/alm/lib/python3.10/site-packages/modelscope/pipelines/__init__.py", line 4, in <module>
    from .base import Pipeline
  File "/home/dmytrodronov/miniconda3/envs/alm/lib/python3.10/site-packages/modelscope/pipelines/base.py", line 16, in <module>
    from modelscope.msdatasets import MsDataset
  File "/home/dmytrodronov/miniconda3/envs/alm/lib/python3.10/site-packages/modelscope/msdatasets/__init__.py", line 2, in <module>
    from .ms_dataset import MsDataset
  File "/home/dmytrodronov/miniconda3/envs/alm/lib/python3.10/site-packages/modelscope/msdatasets/ms_dataset.py", line 24, in <module>
    from modelscope.msdatasets.utils.hf_datasets_util import \
  File "/home/dmytrodronov/miniconda3/envs/alm/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 42, in <module>
    from datasets.utils import _datasets_server, file_utils
ImportError: cannot import name '_datasets_server' from 'datasets.utils' (/home/dmytrodronov/miniconda3/envs/alm/lib/python3.10/site-packages/datasets/utils/__init__.py)
```

My python deps:
```
Package                       Version
----------------------------- --------------------
absl-py                       2.1.0
accelerate                    0.29.3
addict                        2.4.0
aiohttp                       3.9.5
aiosignal                     1.3.1
alabaster                     0.7.16
albumentations                1.3.1
aliyun-python-sdk-core        2.15.1
aliyun-python-sdk-kms         2.16.2
annotated-types               0.6.0
antlr4-python3-runtime        4.9.3
async-timeout                 4.0.3
attrs                         23.2.0
av                            12.0.0
Babel                         2.14.0
black                         24.4.0
blis                          0.7.11
blobfile                      2.1.1
bmt-clipit                    1.0
boto3                         1.34.87
botocore                      1.34.87
cachetools                    5.3.3
catalogue                     2.0.10
certifi                       2024.2.2
cffi                          1.16.0
charset-normalizer            3.3.2
chumpy                        0.70
click                         8.1.7
clip                          1.0
cloudpathlib                  0.16.0
coloredlogs                   15.0.1
confection                    0.1.4
contextlib2                   21.6.0
contourpy                     1.2.1
control-ldm                   0.0.1
crcmod                        1.7
cryptography                  42.0.5
cycler                        0.12.1
cymem                         2.0.8
datasets                      2.19.0
ddpm-guided-diffusion         0.0.0
decorator                     4.4.2
descartes                     1.1.0
diffusers                     0.27.2
dill                          0.3.8
docutils                      0.20.1
easydict                      1.13
easyrobust                    0.2.4
edit-distance                 1.0.6
einops                        0.7.0
embeddings                    0.0.8
emoji                         2.11.0
exceptiongroup                1.2.1
face-alignment                1.4.1
fairscale                     0.4.13
fastai                        2.7.14
fastcore                      1.5.29
fastdownload                  0.0.7
fastprogress                  1.0.3
ffmpeg                        1.4
ffmpeg-python                 0.2.0
filelock                      3.13.4
fire                          0.6.0
flake8                        7.0.0
flatbuffers                   24.3.25
fonttools                     4.51.0
frozenlist                    1.4.1
fsspec                        2024.3.1
ftfy                          6.2.0
future                        1.0.0
fvcore                        0.1.5.post20221221
gast                          0.5.4
grpcio                        1.62.2
huggingface-hub               0.22.2
humanfriendly                 10.0
idna                          3.7
imageio                       2.34.0
imageio-ffmpeg                0.4.9
imagesize                     1.4.1
imgaug                        0.4.0
importlib_metadata            7.1.0
iniconfig                     2.0.0
iopath                        0.1.10
jieba                         0.42.1
Jinja2                        3.1.3
jmespath                      0.10.0
joblib                        1.4.0
kiwisolver                    1.4.5
kornia                        0.7.2
kornia_rs                     0.1.3
langcodes                     3.3.0
lap                           0.4.0
lightning-utilities           0.11.2
llvmlite                      0.42.0
lmdb                          1.4.1
lpips                         0.1.4
lxml                          4.9.4
lyft-dataset-sdk              0.0.8
Markdown                      3.6
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.5.3
mccabe                        0.7.0
mdurl                         0.1.2
megatron-util                 1.3.2
meson                         1.3.2
ml-collections                0.1.1
mmcls                         0.25.0
mmdet                         2.28.2
mmdet3d                       1.0.0a1
mmsegmentation                0.30.0
mock                          5.1.0
modelscope                    1.13.3
moviepy                       1.0.3
mpmath                        1.3.0
multidict                     6.0.5
multiprocess                  0.70.16
murmurhash                    1.0.10
mypy-extensions               1.0.0
nerfacc                       0.2.2
networkx                      3.3
ninja                         1.11.1.1
nltk                          3.8.1
numba                         0.59.1
numpy                         1.26.4
nuscenes-devkit               1.1.11
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.19.3
nvidia-nvjitlink-cu12         12.4.127
nvidia-nvtx-cu12              12.1.105
omegaconf                     2.3.0
onnx                          1.16.0
onnxruntime                   1.17.3
onnxsim                       0.4.36
open-clip-torch               2.24.0
opencv-python                 4.9.0.80
opencv-python-headless        4.9.0.80
opt-einsum                    3.3.0
oss2                          2.18.4
packaging                     24.0
paint-ldm                     0.0.0
pandas                        2.2.2
panopticapi                   0.1
pathspec                      0.12.1
pdfminer.six                  20231228
pdfplumber                    0.11.0
pillow                        10.3.0
pip                           23.3.1
platformdirs                  4.2.0
plotly                        5.21.0
pluggy                        1.4.0
plyfile                       1.0.3
portalocker                   2.8.2
preshed                       3.0.9
prettytable                   3.10.0
proglog                       0.1.10
protobuf                      3.20.3
psutil                        5.9.8
pyarrow                       15.0.2
pyarrow-hotfix                0.6
pybind11                      2.12.0
pyclipper                     1.3.0.post5
pycocotools                   2.0.7
pycodestyle                   2.11.1
pycparser                     2.22
pycryptodome                  3.20.0
pycryptodomex                 3.20.0
pydantic                      2.7.0
pydantic_core                 2.18.1
pyflakes                      3.2.0
Pygments                      2.17.2
PyMCubes                      0.1.4
pyparsing                     3.1.2
pypdfium2                     4.29.0
pyquaternion                  0.9.9
pytest                        8.1.1
pythainlp                     5.0.2
python-crfsuite               0.9.10
python-dateutil               2.9.0.post0
pytorch-lightning             2.2.2
pytz                          2024.1
pyvi                          0.1.1
PyWavelets                    1.6.0
PyYAML                        6.0.1
qudida                        0.0.4
rapid-latex-ocr               0.0.6
regex                         2024.4.16
requests                      2.31.0
rich                          13.7.1
rouge                         1.0.1
s3transfer                    0.10.1
sacremoses                    0.1.1
safetensors                   0.4.3
scikit-image                  0.19.3
scikit-learn                  1.4.2
scipy                         1.13.0
sentencepiece                 0.2.0
seqeval                       1.2.2
setuptools                    68.2.2
Shapely                       1.8.5.post1
shotdetect-scenedetect-lgss   0.0.4
simplejson                    3.19.2
six                           1.16.0
sklearn-crfsuite              0.3.6
smart-open                    6.4.0
smplx                         0.1.28
snowballstemmer               2.2.0
sortedcontainers              2.4.0
spacy                         3.7.4
spacy-legacy                  3.0.12
spacy-loggers                 1.0.5
Sphinx                        7.2.6
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
srsly                         2.4.8
stanza                        1.8.1
subword-nmt                   0.3.8
sympy                         1.12
tabulate                      0.9.0
tenacity                      8.2.3
tensorboard                   2.16.2
tensorboard-data-server       0.7.2
tensorflow-estimator          2.15.0
termcolor                     2.4.0
terminaltables                3.1.10
tf-slim                       1.1.0
thinc                         8.2.3
thop                          0.1.1.post2209072238
threadpoolctl                 3.4.0
tifffile                      2024.4.18
timm                          0.5.4
tokenizers                    0.19.1
toml                          0.10.2
tomli                         2.0.1
torch                         2.2.2
torch-scatter                 2.1.2
torchmetrics                  1.3.2
torchsummary                  1.5.1
torchvision                   0.17.2
tqdm                          4.66.2
transformers                  4.40.0
trimesh                       2.35.39
triton                        2.2.0
typer                         0.9.4
typing_extensions             4.11.0
tzdata                        2024.1
ujson                         5.9.0
urllib3                       2.2.1
utils                         1.0.2
videofeatures-clipit          1.0
Wand                          0.6.13
wasabi                        1.1.2
wcwidth                       0.2.13
weasel                        0.3.4
Werkzeug                      3.0.2
wheel                         0.41.2
xxhash                        3.4.1
yacs                          0.1.8
yapf                          0.40.2
yarl                          1.9.4
zhconv                        1.4.3
zipp                          3.18.1
```

Thanks.

**Comment by decadance-dance** [comment]
`pip install datasets==2.16.1 --force-reinstall` works for me.
