### ISSUE TITLE
关于D4LA数据集下载

### ISSUE THREAD

**Issue by yic666** [AlibabaResearch/AdvancedLiterateMachinery#144]
当我按照要求[quickstart](https://modelscope.cn/datasets/iic/D4LA/quickstart) 运行以下载数据集时，报错如下：
```
2024-05-21 01:13:58,082 - modelscope - INFO - PyTorch version 2.1.0 Found.
2024-05-21 01:13:58,083 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-05-21 01:13:58,146 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 c702eab476dd1d26edfee70bc720afa3 and a total number of 976 components indexed
2024-05-21 01:13:59,704 - modelscope - INFO - dataset_type: 1
Traceback (most recent call last):
  File "down.py", line 3, in <module>
    ds =  MsDataset.load('iic/D4LA')
  File "/usr/local/lib/python3.8/dist-packages/modelscope/msdatasets/ms_dataset.py", line 318, in load
    dataset_inst = remote_dataloader_manager.load_dataset(
  File "/usr/local/lib/python3.8/dist-packages/modelscope/msdatasets/data_loader/data_loader_manager.py", line 132, in load_dataset
    oss_downloader.process()
  File "/usr/local/lib/python3.8/dist-packages/modelscope/msdatasets/data_loader/data_loader.py", line 82, in process
    self._build()
  File "/usr/local/lib/python3.8/dist-packages/modelscope/msdatasets/data_loader/data_loader.py", line 109, in _build
    meta_manager.parse_dataset_structure()
  File "/usr/local/lib/python3.8/dist-packages/modelscope/msdatasets/meta/data_meta_manager.py", line 119, in parse_dataset_structure
    raise FileNotFoundError(
FileNotFoundError: Cannot find dataset meta-files, please fetch meta from modelscope hub.
```
我想知道如何解决这个问题

**Comment by yic666** [comment]
另外，当我采用git的方式时`git clone https://www.modelscope.cn/datasets/iic/D4LA.git`，
下载下来的数据大小不对
```
Cloning into 'D4LA'...
remote: Enumerating objects: 10, done.
remote: Total 10 (delta 0), reused 0 (delta 0), pack-reused 10
Unpacking objects: 100% (10/10), 438.41 KiB | 1.46 MiB/s, done.
```
只有400多k，且压缩文件损坏

**Comment by luochuwei** [comment]
@yic666 安装一下git lfs

**Comment by yic666** [comment]
谢谢，已解决
