### ISSUE TITLE
An error occurred when installing apex

### ISSUE THREAD

**Issue by pjw-cmd** [AlibabaResearch/AdvancedLiterateMachinery#169]
Thank you very much for your contribution. I encountered the following error when installing apex:
(py310) [root apex]# pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
Using pip 24.2 from /data/anaconda3/envs/py310/lib/python3.10/site-packages/pip (python 3.10)
DEPRECATION: --build-option and --global-option are deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11859
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option. 
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Processing /data1/pengjw/AdvancedLiterateMachinery/DocumentUnderstanding/VGT/apex
  Running command pip subprocess to install build dependencies
  Using pip 24.2 from /data/anaconda3/envs/py310/lib/python3.10/site-packages/pip (python 3.10)
  Looking in indexes: https://mirrors.aliyun.com/pypi/simple
  Collecting setuptools
    Using cached setuptools-74.1.2-py3-none-any.whl
  Collecting wheel
    Using cached wheel-0.44.0-py3-none-any.whl
  Installing collected packages: wheel, setuptools
    Creating /tmp/pip-build-env-g6_1kl38/overlay/bin
    changing mode of /tmp/pip-build-env-g6_1kl38/overlay/bin/wheel to 755
  Successfully installed setuptools-74.1.2 wheel-0.44.0
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "/data/anaconda3/envs/py310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/data/anaconda3/envs/py310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/data/anaconda3/envs/py310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-g6_1kl38/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
    File "/tmp/pip-build-env-g6_1kl38/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-g6_1kl38/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
      exec(code, locals())
    File "<string>", line 10, in <module>
  ModuleNotFoundError: No module named 'torch'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /data/anaconda3/envs/py310/bin/python /data/anaconda3/envs/py310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpq6rp6k3p
  cwd: /data1/pengjw/AdvancedLiterateMachinery/DocumentUnderstanding/VGT/apex
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I installed torch in the virtual environment. Would like to ask you have encountered such a problem, how to solve. Looking forward to your reply.

**Comment by carloscaetano** [comment]
@pjw-cmd , I'm facing the same problem. Did you manage how to fix it?
